- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/horizon
