- project:
    # Please try to keep the list of job names sorted alphabetically.
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstack-python3-jobs
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
