- project:
    # Please try to keep the list of job names sorted alphabetically.
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/horizon
